name: Lint
on:
  push:
    branches:
      - revamp-3.0
  pull_request:
    branches:
      - revamp-3.0

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: "**/src/"
