name: Sanity check
on:
  push:
    branches:
      - revamp-3.0
  pull_request:
    branches:
      - revamp-3.0

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Commits Check
    steps:
      - name: Get PR Commits
        id: "get-pr-commits"
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: DCO Check
        uses: tim-actions/dco@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
